### ISSUE TITLE
Configuration option for hue-upnp/PyHue helper to have it listen on a different IP address

### ISSUE THREAD

**Issue by ggiesen** [jimboca/ISYHelper#1]
Is it possible to get a configuration option for the PyHue helper to have the IP it listens on be configurable (I need to have ISYHelper and PyHue/hue-upnp listen on different IP addresses)

**Comment by ggiesen** [comment]
Now that I think about it, it would be useful to be able to specify an explicit IP that ISYHelper should listen on

**Comment by jimboca** [comment]
Yes, that shouldn't be to difficult.  Is this because the device has multiple IP's?

**Comment by ggiesen** [comment]
Yes. Multiple interfaces with multiple IPs.

**Comment by ggiesen** [comment]
Note that just to be clear, ideally ISYHelper and hue-upnp should be able to listen on different IPs. I do this because I have a separate home automation/security LAN, but I have to have hue-upnp listen on my main LAN because upnp isn't routed.

**Comment by jimboca** [comment]
OK, makes sense. I'll look into it.

**Comment by jimboca** [comment]
Fix pushed, see config.example.yaml for info on main host and PyHue host options.  Since i don't have multiple IP's I couldn't completely test, but hopefully it is correct.

**Comment by ggiesen** [comment]
Looks like the PyHue portion is working. The rest interface portion has a few issues though.

ISYHelper: Version 1.08 Started: 2016-01-06 12:23:01.284269
Traceback (most recent call last):
  File "./isyhelper.py", line 30, in <module>
    config = load_config();
  File "/home/ggiesen/ISYHelper/ISYHelper/ISYHelper/**init**.py", line 30, in load_config
    print "isyhelper: host: " + this_host + ":" + port
TypeError: cannot concatenate 'str' and 'int' objects

So looks like you need to cast the port as a string. If I put quotes around it in the config, the error disappears. However, it seems to bind to 0.0.0.0, completely ignoring the host config.

**Comment by ggiesen** [comment]
Looks like it is ignoring the port setting too if I use quotes. Seems to always default to 0.0.0.0:8080

**Comment by jimboca** [comment]
The python web.py module is not straight forward to set the port.  I'm regretting using that module for a simple rest interface and intend to rip it out.  I won't be able to test a workaround until tomorrow.  But in the meantime can you pass the host:port as an argument when you start isyhelper and that should work.

**Comment by ggiesen** [comment]
Yeah it's not a concern for me, since the IP I want it on is the "default" IP for that box. It was mostly about the PyHue module, which is working perfectly. Just though it should be there for completeness.

**Comment by jimboca** [comment]
Great, thanks.  I'll look into it when I have time.

**Comment by jimboca** [comment]
Host and port options are now working
