### ISSUE TITLE
Issue starting ISYHelper with firmware 5.0.11c

### ISSUE THREAD

**Issue by cptechie** [jimboca/ISYHelper#13]
ISYHelper throws ValueError upon startup when connecting to isy994i firmware 5.0.11c.

```
Traceback (most recent call last):
  File "./isyhelper.py", line 72, in <module>
    isy = PyISY.ISY(config['isy']['host'], config['isy']['port'], config['isy']['user'], config['isy']['password'], False, "1.1", logger)
  File "../PyISY/PyISY/ISY.py", line 84, in __init__
    self.nodes = Nodes(self, xml=self.conn.getNodes())
  File "../PyISY/PyISY/Nodes/__init__.py", line 52, in __init__
    self.parse(xml)
  File "../PyISY/PyISY/Nodes/__init__.py", line 183, in parse
    aux_props) = parse_xml_properties(feature)
  File "../PyISY/PyISY/Nodes/node.py", line 70, in parse_xml_properties
    val = int(val.replace(' ', '0'))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by jimboca** [comment]
Looks to be an issue with PyISY, it works for me on the same ISY firmware  so I'll need to look into it. What part of ISYHelper do you need? Everything except the hue emulator is in Polyglot now.

**Comment by cptechie** [comment]
I am using PyHarmony and PyHue. I will also try to debug this when I get some time tonight.

**Comment by jimboca** [comment]
Yes, you should try Polyglot for Harmony it works way better. But you still
need this for PyHue.

**Comment by jimboca** [comment]
I won't have time to look into this tonight, are you running the latest version?
https://github.com/jimboca/ISYHelper#upgrading

**Comment by cptechie** [comment]
Looks like I was a few commits behind. After updating I have a different error message now.

```
Traceback (most recent call last):
  File "./isyhelper.py", line 21, in <module>
    from ISYHelper.Helpers  import Helpers
  File "/home/chintan/isyhelper/ISYHelper/ISYHelper/Helpers/__init__.py", line 11, in <module>
    from .PyHarmony   import PyHarmony
  File "/home/chintan/isyhelper/ISYHelper/ISYHelper/Helpers/PyHarmony.py", line 12, in <module>
    from pyharmony import ha_get_token,ha_get_client
ImportError: cannot import name ha_get_token
```

**Comment by jimboca** [comment]
Yes, it's not compatible with the latest pyharmony code, there's
instructions in the ISYHelper forum on how to downgrade. But if you move to
the nodeserver you can comment out the PyHarmony section 😀

**Comment by cptechie** [comment]
Cool, I will migrate to the nodeserver tonight. Thanks!

**Comment by jimboca** [comment]
Need to fix this since it still happens even with PyHarmony turned off.

**Comment by cptechie** [comment]
Closing this old issue.
