### ISSUE TITLE
Integrate Harmony control

### ISSUE THREAD

**Issue by jimboca** [jimboca/ISYHelper#2]
Looking at pyharmony to integrate.

**Comment by jimboca** [comment]
Fork'ed https://github.com/bkanuka/pyharmony and will give it a try.

**Comment by jimboca** [comment]
This working in the latest version. Just need to add the ability to send any harmony device commands thru the rest interface.

**Comment by ToddLorey** [comment]
Thanks Jim!  Thought I'd commend you here as well.  :+1: 
-Toddimus from UDI forums

**Comment by ToddLorey** [comment]
I was doing some more searching and came across this:  https://github.com/bwssytems/restful-harmony
Seems like they may have already done a lot of what you may be trying to do.  I don't know enough about the guts of your program or what they've done, but I thought it might be applicable and worth a look to save you some time.

**Comment by jimboca** [comment]
Yes, I have seen that and it would have made it easier in a sense, but I don't like Java programs in general, especially running on a RPi, and I don't like how bwsystems copied the hue emulator code and didn't give the original author credit.  For restful harmony at least they did fork it and gave credit where it was due.

**Comment by ToddLorey** [comment]
Valid points.  I want yours to work anyways.  :)

**Comment by jimboca** [comment]
Just pushed the change you can say:
http://harmonyip:8080/MyHarmony/send/command/deviceid/command
e.g. to pause my Tivo I used:
http://192.168.1.77:8080/FamilyRoomHarmony/send/command/28519632/Pause

You can look up the deviceid's and commands with show/devices.

Do a git pull in your ISYHelper directory, and restart isyhelper, if using the new method just run:
sudo systemctl restart isyhelper

I only did minimal testing, so if it works for you I will officially release it.

**Comment by ToddLorey** [comment]
Jim,

Works great!!  I tried from a firefox browser to control two different devices.  All four commands I tried worked.

I’m assuming this will be a “GET” command for the ISY network resource.  Right?  Or is it PUT or POST?

I’ll try now, and might just answer my own question.

Thanks!  You are the man.
-Todd

**Comment by ToddLorey** [comment]
Yup.  Network resource works too.

**Comment by jimboca** [comment]
Awesome, good to hear. Yes I decided on a simple get instead of a post and
passing json in the body for now at least.

**Comment by ToddLorey** [comment]
Only thing to modify would be the note that says:
http://harmonyip:8080/MyHarmony/send/command/deviceid/command
into
http://ISYHelperip:8080/MyHarmony/send/command/deviceid/command

**Comment by jimboca** [comment]
Oh, yes, of course. Thanks!

**Comment by ToddLorey** [comment]
I had figured it out, but others might not get it which could lead to extra support requests.  :)

**Comment by ToddLorey** [comment]
Another feature that would be cool to integrate would be to have a state variable in the ISY that updates when a button on the Harmony remote is pressed (i.e. command sent, activity change, etc.).  This would be similar to the activity ID that you've already set up as an ISY variable, with the exception that it's not "two way" like the activity ID state variable is.  I just need the ISY to know a button was pressed.

The use case would be to act as a kind of "occupancy sensor" to integrate into the ISY program environment.  It could be as simple as a changing heartbeat value (-1 or 1).  Just something to tell me that there's someone in the room controlling the entertainment center.

**Comment by jimboca** [comment]
Yes, that is a great idea!  Can you enter a request as a new issue on
github?

That also reminds me that I've wanted to create a heartbeat for the
ISYHelper back to the ISY just to make sure it is still running...
Currently I use the DateTime module and check that they Hour variable gets
changed once an hour, but a more general way would probably be better.

**Comment by jimboca** [comment]
Actually just thinking about it more... I don't think I have access to that
information from the Harmony to know when any button is pressed... So I
doubt it is possible.
